version: '3'

services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    image: 282865065290.dkr.ecr.us-east-2.amazonaws.com/ms_gateway
    env_file: envvar.txt
    ports:
      - 90:3000
    environment:
      - PORT=3000
    restart: on-failure
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - ms_network
  order:
    build:
      context: .
      dockerfile: order/Dockerfile
    image: 282865065290.dkr.ecr.us-east-2.amazonaws.com/ms_order
    env_file: envvar.txt
    expose:
      - '3010'
    environment:
      - PORT=3010
    restart: on-failure
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - ms_network
  payment:
    build:
      context: .
      dockerfile: payment/Dockerfile
    image: 282865065290.dkr.ecr.us-east-2.amazonaws.com/ms_payment
    env_file: envvar.txt
    environment:
      - PORT=3020
    restart: on-failure
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - ms_network
  store:
    build:
      context: .
      dockerfile: store/Dockerfile
    image: 282865065290.dkr.ecr.us-east-2.amazonaws.com/ms_store
    env_file: envvar.txt
    environment:
      - PORT=3030
    restart: on-failure
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - ms_network
  delivery:
    build:
      context: .
      dockerfile: delivery/Dockerfile
    image: 282865065290.dkr.ecr.us-east-2.amazonaws.com/ms_delivery
    env_file: envvar.txt
    environment:
      - PORT=3040
    restart: on-failure
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - ms_network
  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    image: 282865065290.dkr.ecr.us-east-2.amazonaws.com/ms_auth
    env_file: envvar.txt
    expose:
      - '3050'
    environment:
      - PORT=3050
    restart: on-failure
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - ms_network
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:15672']
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ms_network
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=ElMund03sanch0
    ports:
      - 27017:27107
    networks:
      - ms_network
networks:
  ms_network:
