apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-ms-mongo
  labels:
    app: ms-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-mongo
  template:
    metadata:
      labels:
        app: ms-mongo
    spec:
      containers:
        - name: ms-mongo-pod
          image: mongo
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          env:
            - name: PORT
              value: '3000'
            - name: MONGO_USERNAME
              value: 'root'
            - name: MONGO_PASSWORD
              value: 'ElMund03sanch0'
            - name: MONGO_DATABASE
              value: 'ecommerce'
            - name: MONGO_AUTH
              value: 'admin'
            - name: MONGO_PORT
              value: '27017'
            - name: MONGO_HOST
              value: 'mongo-svc'
            - name: RABBIT_HOST
              value: 'rabbitmq-0.rabbitmq.rabbits.svc.cluster.local'
            - name: ORDER_HOST
              value: 'http://order-svc'
            - name: AUTH_HOST
              value: 'http://auth-svc'
            - name: KEYWORD_SECRET
              value: 'Sup3rSecrat0'
            - name: MONGO_INITDB_ROOT_USERNAME
              value: 'root'
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: 'ElMund03sanch0'
