apiVersion: v1
kind: Pod
metadata:
  name: serverwebnginx3
spec:
  containers:
    - name: contenedor1
      image: python:3.6-alpine
      command:
        [
          "sh",
          "-c",
          'echo "contenedor1" > index.html && python -m http.server 8081',
        ]
    - name: contenedor2
      image: python:3.6-alpine
      command:
        [
          "sh",
          "-c",
          'echo "contenedor1" > index.html && python -m http.server 8082',
        ]
