apiVersion: v1
kind: Secret
metadata:
  name: secret1
type: Opaque
stringData:
  username: administrador
  password: "12345"
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
    - name: mypod
      image: nginx:alpine
      volumeMounts:
        - mountPath: /opt
          name: test-vol
          readOnly: true
  volumes:
    - name: test-vol
      secret:
        secretName: secret1
        items:
          - key: username
            path: usuario.txt
