apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
    - name: test-container
      image: nginx:alpine
      volumeMounts:
        - mountPath: /var/log/nginx
          name: log-vol
  volumes:
    - name: log-vol
      emptyDir: {}
