apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
    - name: envar-demo
      image: nginx:alpine
      env:
        - name: VAR1
          value: "Valor de prueba 1"
        - name: VAR2
          value: "Valor de prueba 2"
        - name: VAR3
          value: "Valor de prueba 3"
