apiVersion: v1
kind: ConfigMap
metadata:
  name: web-nginx-config
  labels:
    app: front
data:
  nginx: |
    server {
        listen       8080;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

            location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vars
data:
  db_host: dev.host.local
  db_user: dev_user
  script: |
    echo DB host es $DB_HOST y DB user es $DB_USER > /usr/share/nginx/html/test.html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels:
    app: front
spec:
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: db_host
                  name: vars
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: db_user
                  name: vars
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-vol
            - mountPath: /opt
              name: script-vol
      volumes:
        - name: nginx-vol
          configMap:
            name: web-nginx-config
            items:
              - key: nginx
                path: default.conf
        - name: script-vol
          configMap:
            name: vars
            items:
              - key: script
                path: script.sh
